name: Upload to COS

on:
  push:
    branches: [ gh-pages ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Setup COSCMD
        run: sudo pip install coscmd

      - name: Configure coscmd
        env:
          SECRET_ID: ${{ secrets.SecretId }}
          SECRET_KEY: ${{ secrets.SecretKey }}
          BUCKET: pages-1251554365
          REGION: ap-guangzhou
        run: coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION

      - name: Upload
        run: coscmd upload -rs --delete -f ./ / --ignore "./.git/*"
